package com.fly.traveloptions.bagservice;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(bd55efd8de3b147542fc866caa9501a1)
 */
@org.kie.api.definition.type.Label(value = "Passenger")
public class Passenger extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Country Code")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String countryCode;
    
    @org.kie.api.definition.type.Label(value = "First Name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String firstName;
    
    @org.kie.api.definition.type.Label(value = "Flyer Status")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String flyerStatus;
    
    @org.kie.api.definition.type.Label(value = "Gender")
    @org.kie.api.definition.type.Position(value = 9)
    private java.lang.String gender;
    
    @org.kie.api.definition.type.Label(value = "Last Name")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String lastName;
    
    @org.kie.api.definition.type.Label(value = "Number Of Bags")
    @org.kie.api.definition.type.Position(value = 6)
    private int numberOfBags;
    
    @org.kie.api.definition.type.Label(value = "Shipping Cost")
    @org.kie.api.definition.type.Position(value = 7)
    private double shippingCost;
    
    @org.kie.api.definition.type.Label(value = "State")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String state;
    
    @org.kie.api.definition.type.Label(value = "Surcharge")
    @org.kie.api.definition.type.Position(value = 8)
    private double surcharge;
    
    @org.kie.api.definition.type.Label(value = "Zip Code")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String zipCode;

    public Passenger() {
    }

    public Passenger(java.lang.String firstName, java.lang.String lastName, java.lang.String flyerStatus, java.lang.String countryCode, java.lang.String zipCode, java.lang.String state, int numberOfBags, double shippingCost, double surcharge, java.lang.String gender) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.flyerStatus = flyerStatus;
        this.countryCode = countryCode;
        this.zipCode = zipCode;
        this.state = state;
        this.numberOfBags = numberOfBags;
        this.shippingCost = shippingCost;
        this.surcharge = surcharge;
        this.gender = gender;
    }


    
    public java.lang.String getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(java.lang.String countryCode) {
        this.countryCode = countryCode;
    }
    
    public java.lang.String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public java.lang.String getFlyerStatus() {
        return this.flyerStatus;
    }

    public void setFlyerStatus(java.lang.String flyerStatus) {
        this.flyerStatus = flyerStatus;
    }
    
    public java.lang.String getGender() {
        return this.gender;
    }

    public void setGender(java.lang.String gender) {
        this.gender = gender;
    }
    
    public java.lang.String getLastName() {
        return this.lastName;
    }

    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }
    
    public int getNumberOfBags() {
        return this.numberOfBags;
    }

    public void setNumberOfBags(int numberOfBags) {
        this.numberOfBags = numberOfBags;
    }
    
    public double getShippingCost() {
        return this.shippingCost;
    }

    public void setShippingCost(double shippingCost) {
        this.shippingCost = shippingCost;
    }
    
    public java.lang.String getState() {
        return this.state;
    }

    public void setState(java.lang.String state) {
        this.state = state;
    }
    
    public double getSurcharge() {
        return this.surcharge;
    }

    public void setSurcharge(double surcharge) {
        this.surcharge = surcharge;
    }
    
    public java.lang.String getZipCode() {
        return this.zipCode;
    }

    public void setZipCode(java.lang.String zipCode) {
        this.zipCode = zipCode;
    }

	@Override
	public String toString() {
		return "Passenger [countryCode=" + countryCode + ", firstName="
				+ firstName + ", flyerStatus=" + flyerStatus + ", gender="
				+ gender + ", lastName=" + lastName + ", numberOfBags="
				+ numberOfBags + ", shippingCost=" + shippingCost + ", state="
				+ state + ", surcharge=" + surcharge + ", zipCode=" + zipCode
				+ "]";
	}
    
    
    
}