package com.fly.traveloptions.bagservice;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(1a8bb9ee825b515187a06ad51f1e6cda)
 */
@org.kie.api.definition.type.Label(value = "Passenger")
public class Passenger  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Country Code")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String countryCode;
    
    @org.kie.api.definition.type.Label(value = "First Name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String firstName;
    
    @org.kie.api.definition.type.Label(value = "Flyer Status")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String flyerStatus;
    
    @org.kie.api.definition.type.Label(value = "Last Name")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String lastName;
    
    @org.kie.api.definition.type.Label(value = "State")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String state;
    
    @org.kie.api.definition.type.Label(value = "Zip Code")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String zipCode;

    public Passenger() {
    }

    public Passenger(java.lang.String firstName, java.lang.String lastName, java.lang.String flyerStatus, java.lang.String countryCode, java.lang.String zipCode, java.lang.String state) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.flyerStatus = flyerStatus;
        this.countryCode = countryCode;
        this.zipCode = zipCode;
        this.state = state;
    }


    
    public java.lang.String getCountryCode() {
        return this.countryCode;
    }

    public void setCountryCode(java.lang.String countryCode) {
        this.countryCode = countryCode;
    }
    
    public java.lang.String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public java.lang.String getFlyerStatus() {
        return this.flyerStatus;
    }

    public void setFlyerStatus(java.lang.String flyerStatus) {
        this.flyerStatus = flyerStatus;
    }
    
    public java.lang.String getLastName() {
        return this.lastName;
    }

    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }
    
    public java.lang.String getState() {
        return this.state;
    }

    public void setState(java.lang.String state) {
        this.state = state;
    }
    
    public java.lang.String getZipCode() {
        return this.zipCode;
    }

	public void setZipCode(java.lang.String zipCode) {
        this.zipCode = zipCode;
    }
	

    @Override
	public String toString() {
		return "Passenger [firstName=" + firstName + ", flyerStatus="
				+ flyerStatus + ", lastName=" + lastName + ", countryCode="
				+ countryCode + ", zipCode=" + zipCode + ", state=" + state
				+ "]";
	}
}