package com.fly.traveloptions.bagservice;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(0b342f35ffd90778e8d23044e59b0b1a)
 */
@org.kie.api.definition.type.Label(value = "Validation Error")
public class ValidationError  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Message")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String message;

    public ValidationError() {
    }

    public ValidationError(java.lang.String message) {
        this.message = message;
    }


    
    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String message) {
        this.message = message;
    }

	@Override
	public String toString() {
		return "ValidationError [message=" + message + "]";
	}
    
    
    
}