package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ID")
   private java.lang.String id;
   @org.kie.api.definition.type.Label(value = "Source")
   private java.lang.String source;
   @org.kie.api.definition.type.Label(value = "FirstName")
   private java.lang.String firstName;
   @org.kie.api.definition.type.Label(value = "Last Name")
   private java.lang.String lastName;
   @org.kie.api.definition.type.Label(value = "Address")
   private java.lang.String address;
   @org.kie.api.definition.type.Label(value = "City")
   private java.lang.String city;
   @org.kie.api.definition.type.Label(value = "State")
   private java.lang.String state;
   @org.kie.api.definition.type.Label(value = "Zip Code")
   private java.lang.Integer zip;

   public Order()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getSource()
   {
      return this.source;
   }

   public void setSource(java.lang.String source)
   {
      this.source = source;
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getState()
   {
      return this.state;
   }

   public void setState(java.lang.String state)
   {
      this.state = state;
   }

   public java.lang.Integer getZip()
   {
      return this.zip;
   }

   public void setZip(java.lang.Integer zip)
   {
      this.zip = zip;
   }

   public Order(java.lang.String id, java.lang.String source,
         java.lang.String firstName, java.lang.String lastName,
         java.lang.String address, java.lang.String city,
         java.lang.String state, java.lang.Integer zip)
   {
      this.id = id;
      this.source = source;
      this.firstName = firstName;
      this.lastName = lastName;
      this.address = address;
      this.city = city;
      this.state = state;
      this.zip = zip;
   }

}