package com.redhat.demos.recovery;


import java.lang.Number;
import java.util.List;

rule "WhichAgents"
	dialect "mvel"
	ruleflow-group "findagents"
	when
		$order : Order( market == "2" )
	$agencylist : ListofAgencies( agency1)
	then
	System.out.println("rule findagents fired")
		//Agency agency1 = new Agency();
		agency1.setName( "XYZ Agent" );
		agency1.setRating( 3 );
	
		System.out.println("fired whichagents rule");
		modify( $agencylist ) {
				setListofagencies( agency1 )
				System.out.prilnt("got here");
		}
		System.out.println("all done");
end