package com.redhat.demos.recovery;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Agency implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Agency() {
    }

}