package com.redhat.demos.recovery;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Agency implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Agent id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label(value = "Agency")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Rating")
   private int rating;
   @org.kie.api.definition.type.Label(value = "market1")
   private java.lang.String market1;
   @org.kie.api.definition.type.Label(value = "Market2")
   private java.lang.String market2;
   @org.kie.api.definition.type.Label(value = "Market3")
   private java.lang.String market3;

   public Agency()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public int getRating()
   {
      return this.rating;
   }

   public void setRating(int rating)
   {
      this.rating = rating;
   }

   public java.lang.String getMarket1()
   {
      return this.market1;
   }

   public void setMarket1(java.lang.String market1)
   {
      this.market1 = market1;
   }

   public java.lang.String getMarket2()
   {
      return this.market2;
   }

   public void setMarket2(java.lang.String market2)
   {
      this.market2 = market2;
   }

   public java.lang.String getMarket3()
   {
      return this.market3;
   }

   public void setMarket3(java.lang.String market3)
   {
      this.market3 = market3;
   }
   public String toString(){
       System.out.println("from agency do"+name+",,,"+rating);
       return name;
   }

   public Agency(java.lang.String id, java.lang.String name, int rating,
         java.lang.String market1, java.lang.String market2,
         java.lang.String market3)
   {
      this.id = id;
      this.name = name;
      this.rating = rating;
      this.market1 = market1;
      this.market2 = market2;
      this.market3 = market3;
   }

}