package com.redhat.demos.recovery;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ListofAgencies implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "List of Agencies")
   private java.util.List<com.redhat.demos.recovery.Agency> listofagencies;

   public ListofAgencies()
   {
   }

   public java.util.List<com.redhat.demos.recovery.Agency> getListofagencies()
   {
      return this.listofagencies;
   }

   public void setListofagencies(
         java.util.List<com.redhat.demos.recovery.Agency> listofagencies)
   {
      this.listofagencies = listofagencies;
   }

   public ListofAgencies(
         java.util.List<com.redhat.demos.recovery.Agency> listofagencies)
   {
      this.listofagencies = listofagencies;
   }
   public String toString(){
       System.out.println("in tostring of loa");
       return Integer.toString(this.listofagencies.size());
   }

}