package com.redhat.demos.recovery;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Order implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ORDER_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "ORDER_ID_GENERATOR", sequenceName = "ORDER_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("First Name")
   private java.lang.String firstName;

   @org.kie.api.definition.type.Label("Last Name")
   private java.lang.String lastName;

   @org.kie.api.definition.type.Label("Address")
   private java.lang.String address;

   @org.kie.api.definition.type.Label("City")
   private java.lang.String city;

   @org.kie.api.definition.type.Label("Source")
   private java.lang.String source;

   @org.kie.api.definition.type.Label("Order ID")
   private java.lang.String orderId;

   @org.kie.api.definition.type.Label("Special Requirements")
   private java.lang.Boolean specialReq;

   @org.kie.api.definition.type.Label("Confidence Rating")
   private int confidencerating;

   @org.kie.api.definition.type.Label("Address Confidence YN")
   private java.lang.Boolean addressconfidence;

   @org.kie.api.definition.type.Label("zip")
   private java.lang.String zip;

   @org.kie.api.definition.type.Label("Market")
   private java.lang.String market;

   @org.kie.api.definition.type.Label(value = "Agency Assigned to")
   private java.lang.String agencyassignedto;

   public Order()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getSource()
   {
      return this.source;
   }

   public void setSource(java.lang.String source)
   {
      this.source = source;
   }

   public java.lang.String getOrderId()
   {
      return this.orderId;
   }

   public void setOrderId(java.lang.String orderId)
   {
      this.orderId = orderId;
   }

   public java.lang.Boolean getSpecialReq()
   {
      return this.specialReq;
   }

   public void setSpecialReq(java.lang.Boolean specialReq)
   {
      this.specialReq = specialReq;
   }

   public java.lang.Boolean getAddressconfidence()
   {
      return this.addressconfidence;
   }

   public void setAddressconfidence(java.lang.Boolean addressconfidence)
   {
      this.addressconfidence = addressconfidence;
   }

   public int getConfidencerating()
   {
      return this.confidencerating;
   }

   public void setConfidencerating(int confidencerating)
   {
      this.confidencerating = confidencerating;
   }

   public String toString()
   {
      System.out.println("city" + city + "source: " + source + "market" + market + "zip" + zip+"ID"+id);
      return ("city" + city + "source: " + source + "market" + market + "zip" + zip+"agency"+agencyassignedto+"ID"+id);
   }

   public java.lang.String getZip()
   {
      return this.zip;
   }

   public void setZip(java.lang.String zip)
   {
      this.zip = zip;
   }

   public java.lang.String getMarket()
   {
      return this.market;
   }

   public void setMarket(java.lang.String market)
   {
      this.market = market;
   }

   public java.lang.String getAgencyassignedto()
   {
      return this.agencyassignedto;
   }

   public void setAgencyassignedto(java.lang.String agencyassignedto)
   {
      this.agencyassignedto = agencyassignedto;
   }

   public Order(java.lang.Long id, java.lang.String firstName,
         java.lang.String lastName, java.lang.String address,
         java.lang.String city, java.lang.String source,
         java.lang.String orderId, java.lang.Boolean specialReq,
         int confidencerating, java.lang.Boolean addressconfidence,
         java.lang.String zip, java.lang.String market,
         java.lang.String agencyassignedto)
   {
      this.id = id;
      this.firstName = firstName;
      this.lastName = lastName;
      this.address = address;
      this.city = city;
      this.source = source;
      this.orderId = orderId;
      this.specialReq = specialReq;
      this.confidencerating = confidencerating;
      this.addressconfidence = addressconfidence;
      this.zip = zip;
      this.market = market;
      this.agencyassignedto = agencyassignedto;
   }

}